permissions:
  tpa: luckytpa.tpa
  tpaccept: luckytpa.tpaccept
  tpdeny: luckytpa.tpdeny


settings:
  time-delay: false
  time-to-teleport: 5 # This is in seconds

messages:
  sent-tpa: "&c&lLuckyTPA &7» &fYou have requested to teleport to &b%player%"
  received-tpa: "&c&lLuckyTPA &7» &fYou have received a teleport request from &b%player%"
  accept: "&a&l[ACCEPT]"
  deny: "&c&l[DENY]"
  no-permission: "&c&lLuckyTPA &7» &cYou don't have permission to run this command!"
  console-cmd: "&c&lLuckyTPA &7» &cOnly players can run this command!"
  player-offline: "&c&lLuckyTPA &7» &fPlayer is offline or doesn't exist"
  no-requests: "&c&lLuckyTPA &7» &fYou don't have any requests"
  you-accepted: "&c&lLuckyTPA &7» &fYou have &aaccepted &fthe teleport request"
  player-accepted: "&c&lLuckyTPA &7» &b%player% &fhas &aaccepted your request"
  player-accepted-timer: "&c&lLuckyTPA &7» &b%player% &fhas &aaccepted your request, teleporting in &c%time% &fseconds"
  you-denied: "&c&lLuckyTPA &7» &fYou have &cdenied &fthe teleport request"
  player-denied: "&c&lLuckyTPA &7» &b%player% &fhas &cdenied your request"